### PR TITLE
[Frontend] load data for stats page from the public folder

### LINKED ISSUE #26: [Frontend] Stats page read data from transcript.json
Will the backend be shut down after the ceremony closed?
If yes, then we might put the `transcript.json` file in the frontend and display it in the `Stats` page.
(Currently the stats are obtained from the backend server.)

### PR DESCRIPTION
**Pull request by kittybest**
**File Changes**
- add `try...catch` method to prevent error in `Ceremony` context functions.
- put current `transcript.json` inside the `public/` folder
- make sure `loadTranscript` function load from the static file if the server is down
- make sure the `<a href="..."` in the `Stats` page load full transcript from the static file if the server is down

**WIP**
- There are so many stats loaded from the server instead of calculated from the transcript.
- To make it clearer, the `WS_SERVER` url is loaded from the `HTTP_SERVER`. We need the connect to the ws_server to get the `ceremony.client` instance, and then most of the data displayed on the Stats page are inside `ceremonyState`.
- The ws_server is deployed at the same time as the http_server, if we wanna keep just the ws_server alive, I think it's hard to split them.
- But ofc we could calculate those data from the transcript. Then I'll need to make sure the calculation logic what I understand is correct.
- Added, we also allow the user to download the latest zkey file of each circuit, ofc this could also be done by putting them in the `public/` folder.

**Discussions**
Wanna make sure do we really need to do this? 
Which means, do we really need to shut down the server after ceremony ends?
Since now the contribute method will be disabled, if we are going to shut down the server after that, we will need to do 
1. download the full transcript (for me, before it shut down, or someone who have access to the backend db could download it for me)
2. put the `transcript.json` file in the `public/` folder and redeploy the frontend
3. These things should be done right after the scheduled closing time

close #26 .

### CODE REVIEW

**Comment by vivianjeng** [comment]
I prefer to shut down the server and keep the frontend page forever
have you ever tried to remove `HTTP_SERVER` and see if it works well?

right now the preview link looks good to me

**Comment by kittybest** [comment]
> I prefer to shut down the server and keep the frontend page forever have you ever tried to remove `HTTP_SERVER` and see if it works well?
> 
> right now the preview link looks good to me

I test by inputing wrong HTTP_SERVER and it works well, let me remove the development one on cloudflare as well.

**Comment by kittybest** [comment]
When playing with the preview URL, I found that I could not load the files from `public/` folder. Not sure if this is the problem of cloudflare or we need to add more settings to config file.

**Comment by vivianjeng** [comment]
> When playing with the preview URL, I found that I could not load the files from `public/` folder. Not sure if this is the problem of cloudflare or we need to add more settings to config file.

oh yeah you need to config webpack to export the `public/` folder
or write a copy script in `yarn build` to manually copy the whole `public/` folder to `build/public`

**Comment by kittybest** [comment]
> > When playing with the preview URL, I found that I could not load the files from `public/` folder. Not sure if this is the problem of cloudflare or we need to add more settings to config file.
> 
> oh yeah you need to config webpack to export the `public/` folder or write a copy script in `yarn build` to manually copy the whole `public/` folder to `build/public`

haha I'm also looking at this way, instead of copying by script, I tried to load files by `file-loader`(but it seems not working), then tried to use another webpack plugin called [copy-webpack-plugin](https://www.npmjs.com/package/copy-webpack-plugin).

**Review by vivianjeng — APPROVED** [review]
LGTM
Thank you

**Pull request merged**
