### PR TITLE
[fix] unauthroized auth token problem

### LINKED ISSUE #5: [FE] Request for New Auth Token
- the token in user's localStorage might not be valid due to some conditions, so user will see the server's loading neverendingly 
- we could expire the token in certain period and request it again 
- or we should add a page to show `unauthorized` instead of endless loading, and add a button to let the user request the auth token again from the server

### PR DESCRIPTION
**Pull request by kittybest**
close #5

### CODE REVIEW

**Review by CJ-Rose — COMMENTED** [review]
@kittybest i don't know how to test this.. like how do i create the condition that causes the auth to be expired? bc if i try to contribute on this fresh deployment, there is no problem, and if i try to contribute on a deployment where i have already contributed, i land back on 'contribution completed' screen as expected.

**Comment by kittybest** [comment]
> @kittybest i don't know how to test this.. like how do i create the condition that causes the auth to be expired? bc if i try to contribute on this fresh deployment, there is no problem, and if i try to contribute on a deployment where i have already contributed, i land back on 'contribution completed' screen as expected.

Sorry for late reply... You need to run your local backend, and since the db is default stored in `:memory:` so if you close the backend and re-open it, the db will be totally different, then the original `authToken` frontend get will end up not in the db, then it should response with `unauthorized` message. Previously, if frontend received `unauthorized` it will lead to endless loading as described in the issue. After revision, if the fe got `unauthorized` message, will request a new `authToken` and load the ceremony again.

**Comment by CJ-Rose** [comment]
@kittybest can you help me understand how to run the backend please? On backend start command, i have error: 'no such file or directory ..../backend/circuits/signup.zkey'. In the README I see:

> ### Copying circuits
> 
> You will need the circuit zkeys you would like to apply contributions to, as well as the ptau file used to generate the circuits. Place these files in `packages/backend/circuits`. These can also be placed elsewhere, but we will assume they are at the previous path in this guide.

can you point me to where i can see an example of the needed `circuits` directory, with the zkeys and ptau file?

**Comment by kittybest** [comment]
> @kittybest can you help me understand how to run the backend please? On backend start command, i have error: 'no such file or directory ..../backend/circuits/signup.zkey'. In the README I see:
> 
> > ### Copying circuits
> > You will need the circuit zkeys you would like to apply contributions to, as well as the ptau file used to generate the circuits. Place these files in `packages/backend/circuits`. These can also be placed elsewhere, but we will assume they are at the previous path in this guide.
> 
> can you point me to where i can see an example of the needed `circuits` directory, with the zkeys and ptau file?

Download the circuits here ⬇️ 
https://pub-6c705682d0d84704aeda74c87d3880ec.r2.dev/circuits.tar.gz
and put them in `backend/` like this ⬇️
image

**Review by CJ-Rose — APPROVED** [review]

**Review by vivianjeng — APPROVED** [review]
please update the backend docker before merge it

**Pull request merged**
